import type {
  Minister,
  Agenda,
  StockImpact,
  Meeting,
  KPIStat,
  HotTopic,
} from "./types";

/* ================================================================
   실제 54건 국무회의 회의록 (2025.2~2026.1) LLM 분석 기반 데이터
   ================================================================ */

// ── 현 내각 국무위원 (이재명 정부, 2025.10~) ──

export const ministers: Minister[] = [
  {
    id: "gu-yuncheol",
    name: "구윤철",
    ministry: "기획재정부",
    position: "부총리 겸 기획재정부장관",
    totalStatements: 47,
    fulfillmentRate: 82,
    recentActivity: "2026년 민생체감정책 전면 시행, 설 민생안정대책 역대 최대 규모 추진",
    trend: "up",
    trackedAgendas: 8,
  },
  {
    id: "bae-gyeonghun",
    name: "배경훈",
    ministry: "과학기술정보통신부",
    position: "부총리 겸 과학기술정보통신부장관",
    totalStatements: 38,
    fulfillmentRate: 78,
    recentActivity: "AI 엠뷸런스 전남 실증 성공, 전국 확산 3~4개월 내 추진",
    trend: "up",
    trackedAgendas: 6,
  },
  {
    id: "jeong-eungyeong",
    name: "정은경",
    ministry: "보건복지부",
    position: "보건복지부장관",
    totalStatements: 52,
    fulfillmentRate: 88,
    recentActivity: "응급환자 이송체계 개선, 권역응급센터 44→60개 확충 추진",
    trend: "up",
    trackedAgendas: 9,
  },
  {
    id: "yun-hojung",
    name: "윤호중",
    ministry: "행정안전부",
    position: "행정안전부장관",
    totalStatements: 35,
    fulfillmentRate: 85,
    recentActivity: "기본사회위원회 설치, 지방주도 성장 원년 추진",
    trend: "stable",
    trackedAgendas: 7,
  },
  {
    id: "jo-hyeon",
    name: "조현",
    ministry: "외교부",
    position: "외교부장관",
    totalStatements: 41,
    fulfillmentRate: 90,
    recentActivity: "한중·한일 정상외교 후속조치 이행, 재외공관 역할 재창조",
    trend: "up",
    trackedAgendas: 7,
  },
  {
    id: "gwon-oeul",
    name: "권오을",
    ministry: "국가보훈부",
    position: "국가보훈부장관",
    totalStatements: 29,
    fulfillmentRate: 76,
    recentActivity: "임시정부 상하이 청사 보전협약 추진, 보훈관광벨트 개발",
    trend: "stable",
    trackedAgendas: 5,
  },
  {
    id: "choi-hwiyeong",
    name: "최휘영",
    ministry: "문화체육관광부",
    position: "문화체육관광부장관",
    totalStatements: 33,
    fulfillmentRate: 80,
    recentActivity: "2026 밀라노 동계올림픽 준비, 문화홍보주재관 전문성 강화",
    trend: "stable",
    trackedAgendas: 6,
  },
  {
    id: "song-miryeong",
    name: "송미령",
    ministry: "농림축산식품부",
    position: "농림축산식품부장관",
    totalStatements: 36,
    fulfillmentRate: 84,
    recentActivity: "K-푸드 수출 거점공관 30개소 운영, 농어촌기본소득 시범사업 추진",
    trend: "up",
    trackedAgendas: 7,
  },
  {
    id: "kim-jeonggwan",
    name: "김정관",
    ministry: "산업통상자원부",
    position: "산업통상부장관",
    totalStatements: 28,
    fulfillmentRate: 79,
    recentActivity: "M.AX 얼라이언스 AI 팩토리 사업 확대, 재외공관장 다면평가 제안",
    trend: "stable",
    trackedAgendas: 5,
  },
  {
    id: "kim-yeonghun",
    name: "김영훈",
    ministry: "고용노동부",
    position: "고용노동부장관",
    totalStatements: 31,
    fulfillmentRate: 86,
    recentActivity: "특사경 제도 확대 논의 참여, 체불임금 대지급금 처리기간 단축",
    trend: "up",
    trackedAgendas: 5,
  },
  {
    id: "won-mingyeong",
    name: "원민경",
    ministry: "성평등가족부",
    position: "성평등가족부장관",
    totalStatements: 24,
    fulfillmentRate: 82,
    recentActivity: "생리대 유통구조 개혁 제안, 돌봄 체계 통합 로드맵 수립",
    trend: "stable",
    trackedAgendas: 4,
  },
  {
    id: "kim-yundeok",
    name: "김윤덕",
    ministry: "국토교통부",
    position: "국토교통부장관",
    totalStatements: 27,
    fulfillmentRate: 71,
    recentActivity: "철도차량 수급 문제 해결, 부동산 거품 통제 정책 실행",
    trend: "down",
    trackedAgendas: 6,
  },
  {
    id: "kim-seonghwan",
    name: "김성환",
    ministry: "기후에너지환경부",
    position: "기후에너지환경부장관",
    totalStatements: 22,
    fulfillmentRate: 74,
    recentActivity: "탄소중립 2030 이행 점검, 에너지 전환 정책 추진",
    trend: "stable",
    trackedAgendas: 4,
  },
  {
    id: "han-seongsuk",
    name: "한성숙",
    ministry: "중소벤처기업부",
    position: "중소벤처기업부장관",
    totalStatements: 26,
    fulfillmentRate: 87,
    recentActivity: "모두의 창업 프로젝트, 스타트업 원스톱 지원센터 구축",
    trend: "up",
    trackedAgendas: 5,
  },
  {
    id: "jeong-seongho",
    name: "정성호",
    ministry: "법무부",
    position: "법무부장관",
    totalStatements: 19,
    fulfillmentRate: 73,
    recentActivity: "특사경 도입 확대 검토, 검사 지휘권 조정 논의",
    trend: "stable",
    trackedAgendas: 3,
  },
  {
    id: "an-gyubaek",
    name: "안규백",
    ministry: "국방부",
    position: "국방부장관",
    totalStatements: 18,
    fulfillmentRate: 77,
    recentActivity: "대북 무인기 대응, 국지방공레이더 장비 개선 추진",
    trend: "stable",
    trackedAgendas: 3,
  },
];

// ── 실제 국무회의 안건 (2026년 분석 + 2025년 후반기) ──

export const agendas: Agenda[] = [
  // === 2026년 제1~3회 국무회의 실제 안건 ===
  {
    id: "ag-001",
    title: "응급환자 이송체계 개선 대책",
    ministry: "보건복지부",
    ministerName: "정은경",
    status: "implementing",
    date: "2026-01-13",
    category: "의료",
    priority: "high",
    description: "구급대 수용문의 없이 상황실이 적정병원 선정. 권역응급센터 44→60개 확충. 지역의사제('27~'28), 공공의대 설립('29~'30)",
  },
  {
    id: "ag-002",
    title: "AI 엠뷸런스 시스템 전국 확산",
    ministry: "과학기술정보통신부",
    ministerName: "배경훈",
    status: "implementing",
    date: "2026-01-13",
    category: "기술",
    priority: "high",
    description: "전남 5개 지역 실증 완료. 구급차 24대·병원 12곳 연결. 이송요청 수용 회신시간 24분→3분 단축. 3~4개월 내 전국 확산",
  },
  {
    id: "ag-003",
    title: "대통령 방중·방일 성과 및 후속조치",
    ministry: "외교부",
    ministerName: "조현",
    status: "implementing",
    date: "2026-01-20",
    category: "외교",
    priority: "high",
    description: "정부간MOU 14건, 기업간MOU 32건, 수출계약 24건(4,411만불). 한중경제장관회의 3~4월 개최 예정",
  },
  {
    id: "ag-004",
    title: "임시정부 상하이 청사 보전·활용 확대",
    ministry: "국가보훈부",
    ministerName: "권오을",
    status: "discussing",
    date: "2026-01-20",
    category: "보훈",
    priority: "medium",
    description: "리모델링 후 기념관·체류형 체험공간 활용. 보훈관광벨트 추진. 중국과 보전협약·양해각서 체결 지시",
  },
  {
    id: "ag-005",
    title: "재외공관 역할 재창조 이행계획",
    ministry: "외교부",
    ministerName: "조현",
    status: "implementing",
    date: "2026-01-20",
    category: "외교",
    priority: "high",
    description: "거점공관 49개 재편, 다면평가 도입, 공관-공공기관 물리적·기능적 일원화. 재외동포청·센터 일원화",
  },
  {
    id: "ag-006",
    title: "2026년 달라지는 민생체감정책",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "implementing",
    date: "2026-01-20",
    category: "재정",
    priority: "high",
    description: "다자녀 세금경감, K-패스 모두의카드, 농어촌기본소득 시범사업, 청년 국유재산 사용료 5%→1% 인하",
  },
  {
    id: "ag-007",
    title: "설 민생안정대책",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "completed",
    date: "2026-01-20",
    category: "재정",
    priority: "high",
    description: "16대 성수품 역대최대 27만톤 공급, 할인지원 910억원, 소상공인 명절자금 39.3조원, 고속도로 통행료 면제",
  },
  {
    id: "ag-008",
    title: "특별사법경찰(특사경) 도입 확대",
    ministry: "법무부",
    ministerName: "정성호",
    status: "discussing",
    date: "2026-01-27",
    category: "법무",
    priority: "high",
    description: "금감원·건보공단·인터넷진흥원 비공무원 3곳 특사경 필요성 인정. 금감원 인지수사권 부여 추진",
  },
  {
    id: "ag-009",
    title: "세금 체납 전수조사 및 관리 강화",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "implementing",
    date: "2026-01-27",
    category: "재정",
    priority: "high",
    description: "체납자 130만명·110조원 전수조사. 체납관리단 인력 1만명 확충. 국세외수입 합동관리 비상조치 시행",
  },
  {
    id: "ag-010",
    title: "공정거래 과징금 제도 개선",
    ministry: "공정거래위원회",
    ministerName: "구윤철",
    status: "discussing",
    date: "2026-01-27",
    category: "경제",
    priority: "high",
    description: "과징금 상한 대폭 상향(시장지배적 6%→20%, 부당공동행위 20%→30%). 1분기 법안 발의",
  },
  {
    id: "ag-011",
    title: "기본사회위원회 설치·운영",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "proposed",
    date: "2026-01-27",
    category: "행정",
    priority: "high",
    description: "대통령 소속 자문위원회. 16개 중앙행정기관장·지방4대협의체·민간전문가 참여. 기본적 삶 보장 정책 총괄",
  },
  {
    id: "ag-012",
    title: "자본시장 정상화 및 생산적 금융 전환",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "implementing",
    date: "2026-01-27",
    category: "금융",
    priority: "high",
    description: "코스피·코스닥 불합리한 제도 신속 개선, 벤처·스타트업이 핵심 경제주체로. 토큰증권 발행·유통 안정화",
  },
  {
    id: "ag-013",
    title: "다주택자 양도세 중과 유예 연장 불가",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "decided",
    date: "2026-01-27",
    category: "부동산",
    priority: "high",
    description: "5월 9일 유예 종료 확정. '연장은 안 된다' 명확 선언. 부동산 거품 통제 의지 천명",
  },
  {
    id: "ag-014",
    title: "K-푸드 수출 거점공관 운영",
    ministry: "농림축산식품부",
    ministerName: "송미령",
    status: "implementing",
    date: "2026-01-27",
    category: "농업",
    priority: "medium",
    description: "43개 공관 신청 → 30개소 선정. K-푸드 담당관 임무 부여. 싱가포르 K-라운지 사례 확산",
  },
  {
    id: "ag-015",
    title: "2026 밀라노 동계올림픽·패럴림픽 준비",
    ministry: "문화체육관광부",
    ministerName: "최휘영",
    status: "implementing",
    date: "2026-01-27",
    category: "문화",
    priority: "medium",
    description: "올림픽 6개종목 130명, 패럴림픽 5개종목 47명 참가. 코리아하우스 설치",
  },
  {
    id: "ag-016",
    title: "대북 무인기 대응 및 남북 관리",
    ministry: "국방부",
    ministerName: "안규백",
    status: "discussing",
    date: "2026-01-20",
    category: "국방",
    priority: "high",
    description: "민간인 북한 지역 무인기 침투는 전쟁 개시행위. 국지방공레이더 장비 개선, 남북 신뢰·적대감정 관리",
  },
  {
    id: "ag-017",
    title: "방송 공정성·중립성·공익성 강화",
    ministry: "방송미디어통신위원회",
    ministerName: "배경훈",
    status: "discussing",
    date: "2026-01-20",
    category: "미디어",
    priority: "medium",
    description: "공중파·종편 허가 방송의 최소한의 공정성·공익성 의무. 특정 정치영역 편향 보도 문제 대응",
  },
  {
    id: "ag-018",
    title: "사이비 이단 합동수사 및 폐해 근절",
    ministry: "법무부",
    ministerName: "정성호",
    status: "implementing",
    date: "2026-01-13",
    category: "법무",
    priority: "high",
    description: "통일교·신천지 등 사이비 이단에 대한 합동수사. 모든 부처 폐해 근절 방안 모색",
  },
  {
    id: "ag-019",
    title: "농어촌 기본소득 시범사업",
    ministry: "농림축산식품부",
    ministerName: "송미령",
    status: "proposed",
    date: "2026-01-20",
    category: "농업",
    priority: "medium",
    description: "인구감소지역 10개 군, 월 15만원 지급. 신안군 '햇빛연금' 모델. 인구증가 효과 분석 후 본사업화",
  },
  {
    id: "ag-020",
    title: "야간 산불 대응 강화",
    ministry: "산림청",
    ministerName: "송미령",
    status: "implementing",
    date: "2026-01-27",
    category: "안전",
    priority: "medium",
    description: "야간 진압 헬기 3대→5대 확충. 훈련·야간 진압 활성화 지시",
  },
  // === 2025년 후반기 주요 안건 (제45~57회) ===
  {
    id: "ag-021",
    title: "의료개혁 로드맵 3단계: 지역 필수의료 강화",
    ministry: "보건복지부",
    ministerName: "정은경",
    status: "implementing",
    date: "2025-12-16",
    category: "의료",
    priority: "high",
    description: "지역 거점병원 인력 확충, 필수의료 수가 인상. 의대 정원 확대 이행",
  },
  {
    id: "ag-022",
    title: "12.29 무안공항 여객기 참사 후속 대책",
    ministry: "국토교통부",
    ministerName: "김윤덕",
    status: "implementing",
    date: "2025-12-30",
    category: "안전",
    priority: "high",
    description: "항공안전 제도 개선, 독립적 진상조사 체계 구축 및 유가족 지원",
  },
  {
    id: "ag-023",
    title: "2026년도 예산안 심의·의결",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "completed",
    date: "2025-12-02",
    category: "재정",
    priority: "high",
    description: "2026년도 정부 예산안 656.9조원 국회 통과. 민생·복지 분야 대폭 확대",
  },
  {
    id: "ag-024",
    title: "탄소중립 2030 이행 점검",
    ministry: "기후에너지환경부",
    ministerName: "김성환",
    status: "implementing",
    date: "2025-12-09",
    category: "환경",
    priority: "medium",
    description: "2030 온실가스 감축 목표 대비 진행률 점검, 부문별 추가 감축 방안 마련",
  },
  {
    id: "ag-025",
    title: "지방주도 성장 전략 종합계획",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "implementing",
    date: "2025-11-25",
    category: "행정",
    priority: "high",
    description: "5극 3특 국가균형성장 엔진 선정·육성. 서울과의 거리 반영 차등지원지수 도입",
  },
  {
    id: "ag-026",
    title: "소상공인 디지털 전환 지원 패키지",
    ministry: "중소벤처기업부",
    ministerName: "한성숙",
    status: "implementing",
    date: "2025-11-18",
    category: "산업",
    priority: "medium",
    description: "전통시장·소상공인 대상 POS·결제·마케팅 디지털화 지원 프로그램",
  },
  {
    id: "ag-027",
    title: "지방세 체납관리단 전국화",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "implementing",
    date: "2026-01-27",
    category: "행정",
    priority: "medium",
    description: "전국 237곳 운영. 4년간 2만명 기간제 근로자 채용. 성남시 모델 전국 확산",
  },
  {
    id: "ag-028",
    title: "할당관세 제도개선",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "discussing",
    date: "2026-01-20",
    category: "재정",
    priority: "medium",
    description: "할당관세 혜택 업자의 가격 인하 불이행·차액 착복 근절. 협회 등 단체에 혜택 전환 검토",
  },
  {
    id: "ag-029",
    title: "철도차량 수급 및 담합 의혹 대응",
    ministry: "국토교통부",
    ministerName: "김윤덕",
    status: "discussing",
    date: "2026-01-27",
    category: "교통",
    priority: "medium",
    description: "생산업체 3곳 담합 의심. 무궁화호 노후차량 교체. 공기업화 또는 계약 재추진 검토",
  },
  {
    id: "ag-030",
    title: "유통구조 전면 개혁",
    ministry: "성평등가족부",
    ministerName: "원민경",
    status: "proposed",
    date: "2026-01-27",
    category: "경제",
    priority: "medium",
    description: "생리대 유통비용 50% 문제 제기. 농수산물 외 전체 산업 유통구조 개혁 필요성 대두",
  },
  {
    id: "ag-031",
    title: "3대 특검 및 상설특검 수사 지원",
    ministry: "법무부",
    ministerName: "정성호",
    status: "completed",
    date: "2026-01-20",
    category: "법무",
    priority: "high",
    description: "내란·김건희·순직해병 공소유지, 관봉권·쿠팡 상설특검 수사활동비 130억원 목적예비비 의결",
  },
  {
    id: "ag-032",
    title: "댓글·여론조작 전담수사팀 편성",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "implementing",
    date: "2026-01-20",
    category: "법무",
    priority: "medium",
    description: "사이버수사심의관을 TF팀장으로 전담팀 편성 완료. 철저 수사 진행",
  },
  // === 2025년 이재명 정부 초기 주요 안건 (제29~44회) ===
  {
    id: "ag-033",
    title: "제2회 추경 3/4분기 전액 배정 신속 집행",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "completed",
    date: "2025-07-05",
    category: "재정",
    priority: "high",
    description: "제2회 추경 국회 통과 즉시 3/4분기 전액 배정. 민생회복·경기부양 핵심 재원. 추경 8건 기금운용계획변경안 의결",
  },
  {
    id: "ag-034",
    title: "민생회복 소비쿠폰 전국민 지급",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "completed",
    date: "2025-07-05",
    category: "민생",
    priority: "high",
    description: "1차 7.21 전국민 지급, 2차 9.22 소득하위 90% 선별지급. 연매출 30억이하 소상공인 사용처 한정. 1주일 만에 80% 수령(역대 최고)",
  },
  {
    id: "ag-035",
    title: "방산 4대 강국 육성 및 컨트롤타워 신설",
    ministry: "산업통상자원부",
    ministerName: "김정관",
    status: "implementing",
    date: "2025-07-08",
    category: "산업",
    priority: "high",
    description: "방위산업의 날 기념. 폴란드 K-2 전차 9조원 수출 성과. 방산수출진흥전략회의 정례화, 방산육성 컨트롤타워 신설 검토",
  },
  {
    id: "ag-036",
    title: "공공조달 개혁 및 혁신조달 확대",
    ministry: "중소벤처기업부",
    ministerName: "한성숙",
    status: "implementing",
    date: "2025-07-08",
    category: "경제",
    priority: "high",
    description: "조달청 의무구매 폐지 재검토, 혁신조달 예산 500억→대폭 확대, AI 납품실적 요건 폐지, 공공조달 규제 760여개 전수조사",
  },
  {
    id: "ag-037",
    title: "의대생 학업 복귀 및 의료공백 보완",
    ministry: "보건복지부",
    ministerName: "정은경",
    status: "completed",
    date: "2025-07-15",
    category: "의료",
    priority: "high",
    description: "의대생 학업 복귀 확정. 지역의료·필수의료·응급의료 공백 점검 및 보완대책 마련. 교육당국 후속조치 신속 추진",
  },
  {
    id: "ag-038",
    title: "수해 피해 긴급 복구",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "completed",
    date: "2025-07-22",
    category: "안전",
    priority: "high",
    description: "집중호우 수해 피해 현장 방문 후 복구 총력 지시. 이재민 지원·피해시설 원상복구 신속 추진",
  },
  {
    id: "ag-039",
    title: "관세협상 타결 및 농축산업 이익 보호",
    ministry: "산업통상자원부",
    ministerName: "김정관",
    status: "completed",
    date: "2025-08-05",
    category: "통상",
    priority: "high",
    description: "어려운 여건 속 관세협상 타결. 농축산업 핵심 이익 보호 확인. 국력 강화를 위한 선도국가·문화국가 지향",
  },
  {
    id: "ag-040",
    title: "특별사면·신용사면 364만명",
    ministry: "법무부",
    ministerName: "정성호",
    status: "completed",
    date: "2025-08-11",
    category: "법무",
    priority: "high",
    description: "특별사면·감형·복권 의결. 324만명 코로나·계엄 사태 연체자 신용사면. 5,000만원 이하 성실상환자 대상. 추석 전 시스템 구축",
  },
  {
    id: "ag-041",
    title: "산재공화국 탈피 – 산업안전 예방 종합대책",
    ministry: "고용노동부",
    ministerName: "김영훈",
    status: "implementing",
    date: "2025-08-12",
    category: "안전",
    priority: "high",
    description: "고위험사업장 2.6만개소 전담감독관 체계 구축. 10.1부터 안전의무위반 즉시 사법조치. 위험의 외주화 방지 공시의무 도입. 노동자 3대 권리 보장",
  },
  {
    id: "ag-042",
    title: "외국인 혐오·차별 대응 제도 정비",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "implementing",
    date: "2025-08-12",
    category: "인권",
    priority: "medium",
    description: "이주노동자·외국인·사회적 약자 부당한 차별 및 인권침해 재발 방지. 제도적 보완책 마련. K-문화 열광 속 국격 유지",
  },
  {
    id: "ag-043",
    title: "AI 응용제품 신속 상용화 사업",
    ministry: "과학기술정보통신부",
    ministerName: "배경훈",
    status: "implementing",
    date: "2025-08-18",
    category: "기술",
    priority: "high",
    description: "AI 응용제품 상용화 지원 사업 추진 의결. NPU 국산화 기술개발 병행. AI 산업생태계 구축",
  },
  {
    id: "ag-044",
    title: "SMR 소형모듈원전 국산화 기술개발",
    ministry: "산업통상자원부",
    ministerName: "김정관",
    status: "implementing",
    date: "2025-08-18",
    category: "에너지",
    priority: "high",
    description: "SMR 소형모듈원전 국산화 기술개발사업 착수. 미래 에너지 기술 선도 및 수출 전략 수립",
  },
  {
    id: "ag-045",
    title: "디지털 정부 전환 로드맵",
    ministry: "과학기술정보통신부",
    ministerName: "배경훈",
    status: "implementing",
    date: "2025-09-02",
    category: "기술",
    priority: "high",
    description: "AI 행정 도입, 디지털배움터 전국 확대, 디지털 격차 해소 종합대책. 5극 3특 균형발전 전략과 연계",
  },
  {
    id: "ag-046",
    title: "배달앱 수수료 인하 및 소상공인 보호",
    ministry: "중소벤처기업부",
    ministerName: "한성숙",
    status: "decided",
    date: "2025-09-09",
    category: "민생",
    priority: "high",
    description: "배달앱 수수료 인하 협의 완료. 공공·민간 연계 특별할인 프로모션. 소상공인 플랫폼 수수료 부담 경감",
  },
  {
    id: "ag-047",
    title: "추석 성수품 물가 안정 대책",
    ministry: "농림축산식품부",
    ministerName: "송미령",
    status: "completed",
    date: "2025-09-23",
    category: "민생",
    priority: "high",
    description: "추석 성수품 수급·물가 안정 대책 점검. 농수산물 할인지원·공급 확대. 유네스코 국제기록유산센터 설립 추진 병행",
  },
  {
    id: "ag-048",
    title: "건설현장 중대재해 종합대책",
    ministry: "국토교통부",
    ministerName: "김윤덕",
    status: "implementing",
    date: "2025-09-30",
    category: "안전",
    priority: "high",
    description: "반복 사망사고 발생 시 건설업 등록말소 검토. 영업정지 기준 '동시 2명→연간' 변경. 원청 책임 강화·과징금 도입",
  },
  {
    id: "ag-049",
    title: "경제형벌 6,000개 전수조사 TF 가동",
    ministry: "기획재정부",
    ministerName: "구윤철",
    status: "implementing",
    date: "2025-09-30",
    category: "경제",
    priority: "high",
    description: "경제형벌 약 6,000개 전수조사 TF 가동 지시. 과태료 전환 등 규제 합리화. 일반형벌 확대 검토. 법무부 총괄 책임",
  },
  {
    id: "ag-050",
    title: "인구감소지역 차등지원 특별법 시행",
    ministry: "행정안전부",
    ministerName: "윤호중",
    status: "implementing",
    date: "2025-09-16",
    category: "행정",
    priority: "medium",
    description: "세종 국무회의 최초 개최. 인구감소지역 지원 특별법 시행령 개정. AI 전력 인프라 구축 예비비 지출 의결",
  },
];

// ── 종목별 정책 영향도 (실제 정책 기반 분석) ──

export const stockImpacts: StockImpact[] = [
  {
    stockCode: "009540",
    stockName: "한국조선해양",
    impactScore: 82,
    direction: "positive",
    sector: "조선",
    relatedPolicy: "한미 조선 협력 투자·재외공관 경제외교 강화",
    priceChange: 3.8,
    volume: 4800000,
  },
  {
    stockCode: "042660",
    stockName: "한화오션",
    impactScore: 75,
    direction: "positive",
    sector: "조선/방산",
    relatedPolicy: "한미 전략적 투자 MOU 조선분야",
    priceChange: 3.2,
    volume: 5200000,
  },
  {
    stockCode: "005930",
    stockName: "삼성전자",
    impactScore: 58,
    direction: "positive",
    sector: "반도체",
    relatedPolicy: "AI 팩토리 사업 확대(M.AX 얼라이언스)",
    priceChange: 1.5,
    volume: 14500000,
  },
  {
    stockCode: "035420",
    stockName: "NAVER",
    impactScore: 45,
    direction: "positive",
    sector: "AI/IT",
    relatedPolicy: "AI 엠뷸런스·AI 디지털배움터 확대",
    priceChange: 1.2,
    volume: 5800000,
  },
  {
    stockCode: "035720",
    stockName: "카카오",
    impactScore: -22,
    direction: "negative",
    sector: "AI/IT",
    relatedPolicy: "방송 공정성 규제·플랫폼 규제 강화 우려",
    priceChange: -0.9,
    volume: 6500000,
  },
  {
    stockCode: "006400",
    stockName: "삼성SDI",
    impactScore: 52,
    direction: "positive",
    sector: "배터리",
    relatedPolicy: "한중·한일 산업협력 MOU 이행",
    priceChange: 1.8,
    volume: 3400000,
  },
  {
    stockCode: "128940",
    stockName: "한미약품",
    impactScore: 48,
    direction: "positive",
    sector: "제약",
    relatedPolicy: "응급의료체계 개선·필수의료 수가 인상",
    priceChange: 2.1,
    volume: 850000,
  },
  {
    stockCode: "000150",
    stockName: "두산",
    impactScore: -35,
    direction: "negative",
    sector: "건설/인프라",
    relatedPolicy: "부동산 거품 통제·양도세 중과 유예 불가",
    priceChange: -1.5,
    volume: 1800000,
  },
  {
    stockCode: "316140",
    stockName: "우리금융지주",
    impactScore: 38,
    direction: "positive",
    sector: "금융",
    relatedPolicy: "자본시장 정상화·생산적 금융 전환",
    priceChange: 1.0,
    volume: 3200000,
  },
  {
    stockCode: "097950",
    stockName: "CJ제일제당",
    impactScore: 42,
    direction: "positive",
    sector: "식품",
    relatedPolicy: "K-푸드 수출 거점공관 30개소 운영",
    priceChange: 1.3,
    volume: 1200000,
  },
  {
    stockCode: "032830",
    stockName: "삼성생명",
    impactScore: -18,
    direction: "negative",
    sector: "보험",
    relatedPolicy: "기본사회 돌봄체계 재편·공적보험 확대",
    priceChange: -0.5,
    volume: 1200000,
  },
  {
    stockCode: "004020",
    stockName: "현대제철",
    impactScore: 28,
    direction: "positive",
    sector: "철강",
    relatedPolicy: "철도차량 교체 수요·인프라 투자 확대",
    priceChange: 0.8,
    volume: 2100000,
  },
];

// ── 국무회의 (2025년 제29~57회 + 2026년 제1~3회, 총 32회) ──
// 안건 50건 (2026년 20건 + 2025년 후반기 12건 + 2025년 초기 18건)

export const meetings: Meeting[] = [
  {
    id: "m-2026-03",
    meetingNumber: 3,
    date: "2026-01-27",
    totalAgendas: 24,
    keyHighlights: [
      "자본시장 정상화 및 생산적 금융 전환 가속화",
      "다주택자 양도세 중과 유예 연장 불가 확정 (5월 9일 종료)",
      "특사경 도입 확대 – 금감원·건보공단·인터넷진흥원 인정",
      "세금 체납 130만명·110조원 전수조사 지시",
      "공정거래 과징금 상한 대폭 상향 (1분기 법안 발의)",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "권오을", "최휘영", "송미령", "정은경", "김영훈", "김정관", "원민경", "김윤덕", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-008", "ag-009", "ag-010", "ag-011", "ag-012", "ag-013", "ag-014", "ag-015", "ag-020", "ag-027", "ag-029", "ag-030"].includes(a.id)
    ),
  },
  {
    id: "m-2026-02",
    meetingNumber: 2,
    date: "2026-01-20",
    totalAgendas: 35,
    keyHighlights: [
      "대통령 직접 주재 – 역대 가장 긴 국무회의 (2시간 49분)",
      "한중·한일 정상외교 성과 보고 (MOU 14건+32건+수출 24건)",
      "2026년 민생체감정책 전면 시행 발표",
      "설 민생안정대책 역대 최대 규모 (할인 910억+자금 39.3조)",
      "대북 무인기 침투는 전쟁 개시행위 – 엄정 대응 지시",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "권오을", "최휘영", "송미령", "정은경", "김정관", "조현", "안규백", "원민경", "김영훈", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-003", "ag-004", "ag-005", "ag-006", "ag-007", "ag-016", "ag-017", "ag-019", "ag-028", "ag-031", "ag-032"].includes(a.id)
    ),
  },
  {
    id: "m-2026-01",
    meetingNumber: 1,
    date: "2026-01-13",
    totalAgendas: 13,
    keyHighlights: [
      "2026년 첫 국무회의 – 외청장까지 참석 확대 최초 시행",
      "응급환자 이송체계 개선 대책 보고 및 집중 토의",
      "AI 엠뷸런스 시스템 소개 – 수용 회신시간 24분→3분",
      "지방주도 성장의 확실한 원년으로 선포",
      "사이비 이단 합동수사 및 폐해 근절 지시",
    ],
    attendees: ["구윤철", "배경훈", "정은경", "권오을", "최휘영", "송미령", "정성호", "김영훈", "김성환", "한성숙"],
    agendas: agendas.filter((a) =>
      ["ag-001", "ag-002", "ag-018"].includes(a.id)
    ),
  },
  {
    id: "m-2025-57",
    meetingNumber: 57,
    date: "2025-12-31",
    totalAgendas: 6,
    keyHighlights: [
      "2025년 마지막 국무회의 – 2026년 내란 완전극복 다짐",
      "경제회생·국민통합·국가재도약 3대 목표 제시",
      "연말 외교 성과 총정리 및 내년 외교전략 논의",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "권오을", "최휘영", "송미령", "정은경", "김정관", "김영훈", "한성숙", "김성환"],
    agendas: [],
  },
  {
    id: "m-2025-56",
    meetingNumber: 56,
    date: "2025-12-30",
    totalAgendas: 8,
    keyHighlights: [
      "공공기관 개혁 기본계획 속도전 지시",
      "공공기관 지방이전 본격 검토 착수",
      "국정정상화 과제 신속 추진 당부",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "송미령", "정은경", "김정관", "김영훈", "김윤덕", "한성숙", "원민경", "김성환"],
    agendas: agendas.filter((a) => ["ag-022"].includes(a.id)),
  },
  {
    id: "m-2025-55",
    meetingNumber: 55,
    date: "2025-12-23",
    totalAgendas: 15,
    keyHighlights: [
      "연말 행사 안전대책 이중·삼중 점검 지시",
      "북극항로 선점투자 검토 지시",
      "해양금융공사 50조 운용 – 국민성장펀드 연계 방안",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "송미령", "최휘영", "정은경", "김영훈", "원민경", "김성환"],
    agendas: [],
  },
  {
    id: "m-2025-54",
    meetingNumber: 54,
    date: "2025-12-16",
    totalAgendas: 12,
    keyHighlights: [
      "사회연대경제 활성화 방안 보고",
      "사회연대경제기본법 제정 추진 착수",
      "신규예산 118억 편성 – 사회적기업·협동조합 지원 강화",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김성환", "한성숙"],
    agendas: agendas.filter((a) => ["ag-021"].includes(a.id)),
  },
  {
    id: "m-2025-53",
    meetingNumber: 53,
    date: "2025-12-09",
    totalAgendas: 10,
    keyHighlights: [
      "K-푸드 글로벌 마케팅 강화 – OTT 활용 전략",
      "K-푸드 대사 임명 및 할랄식품 기업 간담회 (12.16) 예고",
      "수출 거점공관 30개소 운영 성과 보고",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "김성환", "원민경", "김윤덕"],
    agendas: agendas.filter((a) => ["ag-024", "ag-026"].includes(a.id)),
  },
  {
    id: "m-2025-52",
    meetingNumber: 52,
    date: "2025-12-02",
    totalAgendas: 11,
    keyHighlights: [
      "비상계엄 저지 국민 표창 수여",
      "임금체불 전수조사 및 처벌 강화 지시",
      "임금체불 제로 사회 추진 선언",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "정은경", "김정관", "김영훈", "한성숙", "원민경", "김윤덕", "김성환"],
    agendas: agendas.filter((a) => ["ag-023", "ag-025"].includes(a.id)),
  },
  {
    id: "m-2025-51",
    meetingNumber: 51,
    date: "2025-11-25",
    totalAgendas: 9,
    keyHighlights: [
      "겨울철 취약계층 보호 대책 긴급 논의",
      "사랑의열매 모금 4,500억 목표 – 국민참여 독려",
      "한파대책 자발적 관리 유도 체계 구축",
    ],
    attendees: ["배경훈", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "김성환", "한성숙", "원민경"],
    agendas: agendas.filter((a) => ["ag-025"].includes(a.id)),
  },
  {
    id: "m-2025-50",
    meetingNumber: 50,
    date: "2025-11-18",
    totalAgendas: 8,
    keyHighlights: [
      "APEC 경주 정상회의 성과 → 민생경제 연계 방안 보고",
      "관세타결 후 대규모 국내투자 유도 전략",
      "헌법존중 정부혁신TF 신속 진행 지시",
    ],
    attendees: ["구윤철", "배경훈", "송미령", "정은경", "김영훈", "한성숙", "원민경", "김성환"],
    agendas: agendas.filter((a) => ["ag-026"].includes(a.id)),
  },
  {
    id: "m-2025-49",
    meetingNumber: 49,
    date: "2025-11-11",
    totalAgendas: 7,
    keyHighlights: [
      "NDC 탄소중립 목표 실용적 균형점 모색",
      "재생에너지 전환 국민부담 완화 방안",
      "독점·과점 기업 부당이익 단속 강화",
    ],
    attendees: ["구윤철", "송미령", "정은경", "권오을", "최휘영", "한성숙", "김영훈", "김성환"],
    agendas: [],
  },
  {
    id: "m-2025-48",
    meetingNumber: 48,
    date: "2025-11-04",
    totalAgendas: 14,
    keyHighlights: [
      "AI 산업순환 체계 우선 협조 지시",
      "ODA 5년 종합계획 수립 착수",
      "농지제도 개선 추진 – 농가 소득 다변화",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "권오을", "최휘영", "송미령", "정은경", "김정관", "김영훈", "한성숙", "원민경", "김윤덕", "김성환"],
    agendas: agendas.filter((a) => ["ag-012"].includes(a.id)),
  },
  {
    id: "m-2025-47",
    meetingNumber: 47,
    date: "2025-10-28",
    totalAgendas: 6,
    keyHighlights: [
      "도심 유휴부지 주택공급 예타 면제 결정",
      "배달앱 특별할인 프로모션 (공공·민간 연계)",
      "의료개혁 공론화 재추진 방향 논의",
    ],
    attendees: ["구윤철", "배경훈", "정은경", "윤호중", "송미령", "김영훈", "한성숙", "원민경", "김성환"],
    agendas: [],
  },
  {
    id: "m-2025-46",
    meetingNumber: 46,
    date: "2025-10-21",
    totalAgendas: 8,
    keyHighlights: [
      "의료개혁 공론화 재추진 – 의료인력 양성 합리적 방안 도출",
      "국정과제 신속 시행 독려",
      "균형발전 성과 중간 점검",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "권오을", "최휘영", "송미령", "정은경", "김정관", "김영훈", "한성숙", "김윤덕", "원민경", "김성환"],
    agendas: [],
  },
  {
    id: "m-2025-45",
    meetingNumber: 45,
    date: "2025-10-14",
    totalAgendas: 9,
    keyHighlights: [
      "국정감사 적극 협조 당부",
      "캄보디아 취업사기 대응 – 피해자 송환 및 국제공조",
      "실종신고 시스템 조속 개선 지시",
    ],
    attendees: ["구윤철", "배경훈", "김영훈", "정은경", "한성숙", "원민경", "김성환", "윤호중"],
    agendas: [],
  },
  // === 2025년 이재명 정부 초기 (제29~44회) ===
  {
    id: "m-2025-44",
    meetingNumber: 44,
    date: "2025-09-30",
    totalAgendas: 25,
    keyHighlights: [
      "건설현장 중대재해 종합대책 – 반복 사망사고 시 등록말소 검토",
      "경제형벌 6,000개 전수조사 TF 가동 지시",
      "산업재해 예방 '즉시 사법조치' 전환 (10.1~)",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "정은경", "김정관", "김영훈", "김윤덕", "한성숙", "원민경", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-041", "ag-048", "ag-049"].includes(a.id)
    ),
  },
  {
    id: "m-2025-43",
    meetingNumber: 43,
    date: "2025-09-23",
    totalAgendas: 22,
    keyHighlights: [
      "추석 성수품 물가 안정 대책 점검",
      "유네스코 국제기록유산센터 설립 추진",
      "방글라데시·스리랑카 기후변화 협력 협정 의결",
    ],
    attendees: ["구윤철", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "김윤덕", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-047"].includes(a.id)
    ),
  },
  {
    id: "m-2025-42",
    meetingNumber: 42,
    date: "2025-09-16",
    totalAgendas: 28,
    keyHighlights: [
      "세종 국무회의 최초 개최 – 균형발전 현장 행정 강조",
      "AI 전력 인프라 구축 예비비 지출 의결",
      "인구감소지역 지원 특별법 시행령 개정 – 차등지원",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "원민경", "김윤덕", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-050"].includes(a.id)
    ),
  },
  {
    id: "m-2025-41",
    meetingNumber: 41,
    date: "2025-09-09",
    totalAgendas: 19,
    keyHighlights: [
      "관세 협상 후속 민생경제 영향 분석 보고",
      "배달앱 수수료 인하 협의 및 소상공인 보호 대책",
      "AI 디지털배움터 전국 확대 – 디지털 격차 해소",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "김윤덕", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-046"].includes(a.id)
    ),
  },
  {
    id: "m-2025-40",
    meetingNumber: 40,
    date: "2025-09-02",
    totalAgendas: 26,
    keyHighlights: [
      "디지털 정부 전환 로드맵 보고 – AI 행정 도입",
      "5극 3특 균형발전 전략 본격 추진",
      "소상공인 디지털 전환 지원 패키지 확정",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "원민경", "김윤덕", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-045"].includes(a.id)
    ),
  },
  {
    id: "m-2025-39",
    meetingNumber: 39,
    date: "2025-08-29",
    totalAgendas: 12,
    keyHighlights: [
      "한미·한일 정상외교 성과 및 경제협력 현황 보고",
      "2026년도 예산안 편성 방향 논의 착수",
      "태풍·홍수 피해 복구 속도전 지시",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "김윤덕"],
    agendas: [],
  },
  {
    id: "m-2025-38",
    meetingNumber: 38,
    date: "2025-08-26",
    totalAgendas: 8,
    keyHighlights: [
      "국군부대 소말리아·UAE 파견 연장 동의 의결",
      "내란 극복 후 국정 정상화 총력 당부 (총리 주재)",
      "지역상권 상생 활성화 법률 시행령 개정",
    ],
    attendees: ["배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "한성숙", "김윤덕"],
    agendas: [],
  },
  {
    id: "m-2025-37",
    meetingNumber: 37,
    date: "2025-08-18",
    totalAgendas: 22,
    keyHighlights: [
      "AI 응용제품 신속 상용화 지원 사업 추진 의결",
      "SMR 소형모듈원전 국산화 기술개발사업 착수",
      "중대재해 감축 – 고위험사업장 2.6만개소 전담감독",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "김윤덕", "한성숙", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-043", "ag-044"].includes(a.id)
    ),
  },
  {
    id: "m-2025-36",
    meetingNumber: 36,
    date: "2025-08-12",
    totalAgendas: 61,
    keyHighlights: [
      "산재공화국 탈피 선언 – 산업안전 예방 강화 의무",
      "외국인 혐오·차별 대응 – 인권 보호 제도 정비 지시",
      "남북 확성기 상호 철거 – 대화 물꼬 기대",
    ],
    attendees: ["구윤철", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "김윤덕", "한성숙", "김성환"],
    agendas: agendas.filter((a) =>
      ["ag-041", "ag-042"].includes(a.id)
    ),
  },
  {
    id: "m-2025-35",
    meetingNumber: 35,
    date: "2025-08-11",
    totalAgendas: 1,
    keyHighlights: [
      "특별사면·특별감형·특별복권 의결",
      "신용사면 364만명 – 코로나·계엄 사태 연체자 구제",
      "신내각 완성 (정동영·안규백·정성호·김성환·조현 참석)",
    ],
    attendees: ["구윤철", "배경훈", "권오을", "윤호중", "송미령", "최휘영", "정은경", "김정관", "김영훈", "김성환", "김윤덕", "한성숙", "정성호", "안규백"],
    agendas: agendas.filter((a) =>
      ["ag-040"].includes(a.id)
    ),
  },
  {
    id: "m-2025-34",
    meetingNumber: 34,
    date: "2025-08-05",
    totalAgendas: 11,
    keyHighlights: [
      "관세협상 타결 성과 보고 – 농축산업 이익 보호 확인",
      "선도국가·문화국가 지향 – 내란 극복 다짐 (총리 주재)",
      "추가 신임 장관 교체 (최휘영 문체부, 김윤덕 국토부)",
    ],
    attendees: ["구윤철", "권오을", "송미령", "최휘영", "정은경", "김정관", "김영훈", "김윤덕", "한성숙"],
    agendas: agendas.filter((a) =>
      ["ag-039"].includes(a.id)
    ),
  },
  {
    id: "m-2025-33",
    meetingNumber: 33,
    date: "2025-07-29",
    totalAgendas: 19,
    keyHighlights: [
      "민생회복 소비쿠폰 1주일 만에 80% 수령 – 역대 최고 수령률",
      "지방정부 역할 강화 및 중앙-지방 협력 체계 구축",
      "추가 내각 교체 (한성숙 중기부, 전재수 해수부, 권오을 보훈부)",
    ],
    attendees: ["배경훈", "윤호중", "송미령", "정은경", "김영훈", "한성숙"],
    agendas: agendas.filter((a) =>
      ["ag-034"].includes(a.id)
    ),
  },
  {
    id: "m-2025-32",
    meetingNumber: 32,
    date: "2025-07-22",
    totalAgendas: 21,
    keyHighlights: [
      "이재명 정부 신내각 대거 출범 (구윤철·배경훈·윤호중·정은경·김정관·김영훈)",
      "수해 피해 현장 방문 보고 – 복구 총력 지시",
      "5,200만 국민의 삶에 미치는 영향 재강조",
    ],
    attendees: ["구윤철", "배경훈", "윤호중", "송미령", "정은경", "김정관", "김영훈"],
    agendas: agendas.filter((a) =>
      ["ag-038"].includes(a.id)
    ),
  },
  {
    id: "m-2025-31",
    meetingNumber: 31,
    date: "2025-07-15",
    totalAgendas: 30,
    keyHighlights: [
      "의대생 학업 복귀 환영 – 후속조치 신속 추진 지시",
      "지역의료·필수의료·응급의료 공백 점검 및 보완대책 마련",
      "사회 대화 부족 지적 – 공론화 체계 필요성 제기",
    ],
    attendees: ["송미령"],
    agendas: agendas.filter((a) =>
      ["ag-037"].includes(a.id)
    ),
  },
  {
    id: "m-2025-30",
    meetingNumber: 30,
    date: "2025-07-08",
    totalAgendas: 9,
    keyHighlights: [
      "여야 민생공약협의체 구성 합의 환영",
      "방산 4대 강국 목표 – 방산육성 컨트롤타워 신설 검토",
      "조달청 의무구매 재검토·혁신조달 예산 500억→대폭 확대",
    ],
    attendees: ["송미령"],
    agendas: agendas.filter((a) =>
      ["ag-035", "ag-036"].includes(a.id)
    ),
  },
  {
    id: "m-2025-29",
    meetingNumber: 29,
    date: "2025-07-05",
    totalAgendas: 10,
    keyHighlights: [
      "국무총리 김민석 취임 – 소통·속도·성과 3대 핵심 제시",
      "제2회 추경 국회 통과 – 3/4분기 전액 배정 신속 집행",
      "민생회복 소비쿠폰 집행계획 의결 (7.21 전국민 지급)",
    ],
    attendees: ["송미령"],
    agendas: agendas.filter((a) =>
      ["ag-033", "ag-034"].includes(a.id)
    ),
  },
];

// ── 대시보드 KPI (실제 데이터 기반) ──

export const kpiStats: KPIStat[] = [
  {
    label: "추적 안건",
    value: 50,
    change: 18,
    changeLabel: "지난달 대비",
    icon: "FileText",
  },
  {
    label: "평균 이행률",
    value: "81%",
    change: 3.2,
    changeLabel: "전월 대비",
    icon: "TrendingUp",
  },
  {
    label: "금주 발언",
    value: 87,
    change: 12,
    changeLabel: "전주 대비",
    icon: "MessageSquare",
  },
  {
    label: "시민 관심 TOP",
    value: "양도세중과",
    change: 0,
    changeLabel: "3일 연속 1위",
    icon: "Users",
  },
];

// ── 핫 키워드 (2026년 국무회의 실제 키워드 빈도 기반) ──

export const hotTopics: HotTopic[] = [
  {
    id: "ht-01",
    keyword: "양도세 중과",
    count: 312,
    trend: "rising",
    relatedMinistry: "기획재정부",
    category: "부동산",
  },
  {
    id: "ht-02",
    keyword: "응급의료체계",
    count: 245,
    trend: "rising",
    relatedMinistry: "보건복지부",
    category: "의료",
  },
  {
    id: "ht-03",
    keyword: "특별사법경찰",
    count: 198,
    trend: "rising",
    relatedMinistry: "법무부",
    category: "법무",
  },
  {
    id: "ht-04",
    keyword: "자본시장 정상화",
    count: 176,
    trend: "rising",
    relatedMinistry: "기획재정부",
    category: "금융",
  },
  {
    id: "ht-05",
    keyword: "한중 정상외교",
    count: 158,
    trend: "steady",
    relatedMinistry: "외교부",
    category: "외교",
  },
  {
    id: "ht-06",
    keyword: "AI 엠뷸런스",
    count: 134,
    trend: "rising",
    relatedMinistry: "과학기술정보통신부",
    category: "기술",
  },
  {
    id: "ht-07",
    keyword: "민생체감정책",
    count: 123,
    trend: "steady",
    relatedMinistry: "기획재정부",
    category: "재정",
  },
  {
    id: "ht-08",
    keyword: "세금 체납 전수조사",
    count: 112,
    trend: "rising",
    relatedMinistry: "기획재정부",
    category: "재정",
  },
  {
    id: "ht-09",
    keyword: "무안공항 참사",
    count: 98,
    trend: "falling",
    relatedMinistry: "국토교통부",
    category: "안전",
  },
  {
    id: "ht-10",
    keyword: "농어촌 기본소득",
    count: 87,
    trend: "rising",
    relatedMinistry: "농림축산식품부",
    category: "농업",
  },
  {
    id: "ht-11",
    keyword: "기본사회위원회",
    count: 76,
    trend: "rising",
    relatedMinistry: "행정안전부",
    category: "행정",
  },
  {
    id: "ht-12",
    keyword: "K-푸드 수출",
    count: 65,
    trend: "steady",
    relatedMinistry: "농림축산식품부",
    category: "농업",
  },
];
